language: cpp
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq
        freeglut3-dev
        libglew-dev
        liblua5.1-dev
        libopenal-dev
        libphysfs-dev
        libsdl-image1.2-dev
        libsdl-net1.2-dev
        libsdl-ttf2.0-dev
        libtinyxml-dev
        libvorbis-dev
        python2.7-dev

script:
  - ./build.sh
