os: linux
dist: trusty
group: stable
language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - freeglut3-dev
      - g++-4.8
      - gcc-4.8
      - libglew-dev
      - liblua5.1-dev
      - libopenal-dev
      - libphysfs-dev
      - libsdl-image1.2-dev
      - libsdl-net1.2-dev
      - libsdl-ttf2.0-dev
      - libtinyxml-dev
      - libvorbis-dev
      - python2.7-dev
script:
  - ./build.sh
